### ISSUE TITLE
Redirection back to create account page

### ISSUE THREAD

**Issue by divergentdave** [dpitch40/telepict#5]
During the account creation flow, the POST to /create_account renders the login template, so that the user can log in immediately after successful account creation. When this template renders, it checks the request path and puts the URL for /create_account in the redirect_url hidden input. Thus, after the user successfully logs in, they are sent back to the create account page, rather than the home page.

Either the conditions inside the login template should be changed to avoid this, or the whole flow should be redone, using POST-to-GET refresh redirects, in a way that avoids the same issue.

**Comment by dpitch40** [comment]
This should be fixed now.
