### ISSUE TITLE
Use PNG compression for image uploads

### ISSUE THREAD

**Issue by divergentdave** [dpitch40/telepict#6]
Currently, a homebrew image compression format is used for image uploads, which encodes pixel coordinates and colors of all non-blank pixels. This is interpreted on the server side, and the images are compressed into JPEGs. It would be simpler and more efficient to use https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL to encode the canvas image as a PNG, and upload that. PNG is well suited for line drawings.

**Comment by Zarel** [comment]
For the record, I totally already talked to Other David about these things in the group chat. :p

![image](https://user-images.githubusercontent.com/551184/86519738-abc87d80-bdf2-11ea-992a-42e86036459b.png)

![image](https://user-images.githubusercontent.com/551184/86519744-bc78f380-bdf2-11ea-875d-95ef5ef2a3c8.png)

**Comment by Zarel** [comment]
https://devdocs.io/dom/htmlcanvaselement/todataurl

Incidentally, `toDataURL` also supports JPEG compression levels, on the off chance that's preferable.
